### ISSUE TITLE
Saving admin Password in Browser. Cannot use feature create users via email when we have active the PP rule "At least 8 characters are required."

### ISSUE THREAD

**Issue by davitol** [owncloud/password_policy#228]
### Steps

1. Login as admin
2. Save your Password in the browser (Firefox in my test)
3. Create rule password At least 8 characters are required and save
4. Create a user "user1" using email

### Current Behavior

User is not created due to the PP rule due to it is taking into account admin password(see below)

<img width="961" alt="Screen Shot 2019-06-26 at 13 05 57" src="https://user-images.githubusercontent.com/10596560/60175352-a31e8e00-9813-11e9-8aea-c9ed1ee28309.png">

It is supposed that when creating a new user via mail a 20 characters provisional pwd is created (see code below)

https://github.com/owncloud/core/blob/v10.2.0/settings/Controller/UsersController.php#L446-L455

## ownCloud log

No logs shown in owncloud.log

**Note**

Reproduced in oC 10.2.0 and 10.2.1 (I will check in earlier versions just in case it could be a regression)

**Comment by phil-davis** [comment]
This is really annoying when testing, until you have worked out what is happening. See my comment https://github.com/owncloud/core/issues/35743#issuecomment-508529972

The server validates that password against the policy settings. If it does not happen to match the policy settings, then you get an error message. 

If it does meet the policy settings then I think it will be saved as the initial "random" password of the new user. That is not really a problem, because the new user has no idea what that password is and it will be encrypted anyway. The new user sets their own first password from the link in the email that they receive.

**Comment by davitol** [comment]
Seems to be fixed in oC 10.3.2.
